before activation: /home/b5an/morganator.b5an/miniforge3/envs/mpi_env/bin/python
Lmod Warning:
'cray-mpich' requires a network targeting module to be loaded.
Try 'module avail craype-network' to list the available network
 targeting modules. 
While processing the following module(s):
    Module fullname    Module Filename
    ---------------    ---------------
    PrgEnv-cray/8.6.0  /opt/cray/pe/lmod/modulefiles/core/PrgEnv-cray/8.6.0.lua

Found existing installation: mpi4py 4.1.1
Uninstalling mpi4py-4.1.1:
  Successfully uninstalled mpi4py-4.1.1
Collecting mpi4py
  Using cached mpi4py-4.1.1-cp311-cp311-manylinux2014_aarch64.manylinux_2_17_aarch64.whl.metadata (16 kB)
Using cached mpi4py-4.1.1-cp311-cp311-manylinux2014_aarch64.manylinux_2_17_aarch64.whl (1.3 MB)
Installing collected packages: mpi4py
Successfully installed mpi4py-4.1.1
after activation: /home/b5an/morganator.b5an/miniforge3/envs/mpi_env/bin/python
Traceback (most recent call last):
  File "/lus/lfs1aip2/projects/b5an/ben_morgan/parallelism/mpi/mpi_hello_world.py", line 1, in <module>
    from mpi4py import MPI
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1138, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1078, in _find_spec
  File "/home/b5an/morganator.b5an/miniforge3/envs/mpi_env/lib/python3.11/site-packages/mpi4py/_mpiabi.py", line 290, in find_spec
    mpiabi_suffix = _get_mpiabi_suffix(fullname)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b5an/morganator.b5an/miniforge3/envs/mpi_env/lib/python3.11/site-packages/mpi4py/_mpiabi.py", line 276, in _get_mpiabi_suffix
    mpiabi = _get_mpiabi()
             ^^^^^^^^^^^^^
  File "/home/b5an/morganator.b5an/miniforge3/envs/mpi_env/lib/python3.11/site-packages/mpi4py/_mpiabi.py", line 258, in _get_mpiabi
    mpiabi = _get_mpiabi_from_libmpi(libmpi)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b5an/morganator.b5an/miniforge3/envs/mpi_env/lib/python3.11/site-packages/mpi4py/_mpiabi.py", line 217, in _get_mpiabi_from_libmpi
    lib = _dlopen_libmpi(libmpi)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b5an/morganator.b5an/miniforge3/envs/mpi_env/lib/python3.11/site-packages/mpi4py/_mpiabi.py", line 210, in _dlopen_libmpi
    raise RuntimeError("\n".join(errors))
RuntimeError: cannot load MPI library
/home/b5an/morganator.b5an/.local/lib: cannot open shared object file: No such file or directory
/home/b5an/morganator.b5an/miniforge3/envs/mpi_env/lib/libmpi.so: cannot open shared object file: No such file or directory
/home/b5an/morganator.b5an/miniforge3/envs/mpi_env/lib/libmpi.so.12: cannot open shared object file: No such file or directory
/home/b5an/morganator.b5an/miniforge3/envs/mpi_env/lib/libmpi.so.40: cannot open shared object file: No such file or directory
libmpi.so: cannot open shared object file: No such file or directory
libmpi.so.12: cannot open shared object file: No such file or directory
libmpi.so.40: cannot open shared object file: No such file or directory
